@startuml
'https://plantuml.com/class-diagram

class Alumno {
    - Materia[] materiasAprobadas


}

class Inscripcion {
    - Materia[] materiasPropuestas
    + boolean aprobada()
}

class Materia {
    - Materia[] correlativas
    + boolean cumpleTodasCorrelativas(Materia[] materias)
}

@enduml